# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/albarregas_db
spring.datasource.username=postgres
spring.datasource.password=admin

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# PUERTO DEL SERVIDOR BACKEND
# ===============================
server.port=8080